### PR TITLE
Added searching algorithms

### PR DESCRIPTION
**Pull request by mahipalimkar**
This PR introduces four fundamental searching algorithms—Linear Search, Binary Search, Breadth-First Search (BFS), and Depth-First Search (DFS)—to the repository. These algorithms cover both array-based searching and graph traversal techniques, which I added in the searching folder.

### CODE REVIEW

**Comment by mahipalimkar** [comment]
Hello @panditakshay402 . I made a pr adding 4 searching algorithms in your searching folder.

**Review by panditakshay402 — APPROVED** [review]

**Review by panditakshay402 — APPROVED** [review]

**Comment by mahipalimkar** [comment]
Hello. This repo has been excluded from hacktoberfest again I believe. Please check.

**Comment by panditakshay402** [comment]
> Hello. This repo has been excluded from hacktoberfest again I believe. Please check. @panditakshay402

@mahipalimkar Hey Use any other repo and add code there.

**Comment by mahipalimkar** [comment]
Hello. This repo has been excluded from hacktoberfest again I believe. Please check

This issue cant be fixed?@panditakshay402

**Comment by mahipalimkar** [comment]
This issue cant be fixed?@panditakshay402

**Comment by panditakshay402** [comment]
> This issue cant be fixed?@panditakshay402

@mahipalimkar Its takes times and times were not defined.

**Pull request merged**
